env: "local" #local, dev, prod
storage_path: 
http_server: 
  address: "localhost:8082"
  timeout: 4s #время на обработку запроса (прием-ответ клиенту)
  idle_timeout: 60s # время жизни соединения с клиентом